### ISSUE TITLE
CRAN task view proposal: PowerAnalysis

### ISSUE THREAD

**Issue by statisfactions** [cran-task-views/ctv#41] opened 2022-11-28 15:08 UTC
## Scope
The proposed CRAN Task View would guide people towards R packages that support power analysis. We use the term "power analysis" to generally encompass what has also been called "design analysis" — examining how study design parameters (e.g., sample size, statistical test and effect size) can affect expected statistical properties of the study. Here we aggregate power analysis packages, including traditional frequentist power analysis and sample size planning, as well as credible interval coverage, model convergence rates, etc. 

The task view would be organized alphabetically by the method employed: e.g. mixed models (supported by pwr2ppl, pamm, simglm) and non-inferiority trial (supported by epiR, blindrecalc) are presented in separate sections; this means that packages that support multiple tests may appear in multiple sections, which creates some duplication but has the benefit of showing related packages for a test in the same place.

We include packages with both formula-based power calculations for specific statistical tests (e.g. `pwr2ppl`) as well as simulation-based methods (e.g. `sempower`). We also include packages like `rddapp` that have power/design analysis as a prominent feature even if the package also performs estimation. We have excluded packages that are only focused on estimation of any specific methods; we have also excluded general packages that *in principle* could be useful for power analysis but have no focus on providing that functionality, e.g. `tidyverse` packages could be helfpully used for creating a simulation for power analysis but has no advertised focus on that. In contrast, we would include general simulation packages like `DeclareDesign` or `simpr` that have an express focus on design analysis, along with functionality for evaluating specific designs.

## Packages
A [draft task view](https://github.com/statisfactions/ctv-power/blob/main/ctv-power.md) is available, which is organized by topic. We are grateful that this work was supported through an R Consortium Grant.

Proposed core packages:
  - `epiR`
  - `FDRsampsize`
  - `MKpower`
  - `PASSED`
  - `pwr`
  - `pwr2ppl`
  - `WebPower`

## Overlap
Since the proposed Power Analysis task view covers the power analysis for a range of techniques, there is some minor overlap with other CRAN Task Views that mention power analysis.  For instance, the Psychometrics CRAN Task View mentions the `pwrRasch` package, which computes power analysis for a type of psychometric analysis; this package would also appear in the proposed Power Analysis task view. Power analysis does not play a large role in any other task views, so we expect there will only be handful of overlapping packages. We believe the difference in focus between this and other task views justifies this minor degree of overlap.

## Maintainers
Richard Webster
Ethan Brown

**Comment by zeileis** [comment] 2022-11-28 20:45
Thanks for the proposal! Some quick first impressions:

* The topic would certainly be of interest to practitioners. It seems reasonably well separated from other task views and the inclusion/exclusion criteria are mostly clear (see also below).
* The biggest drawback in my opinion is the structure. You don't get much value added from all those packages being presented together because you need to search for a suitable headline and then can only look at those packages. For example, a natural family of models I'm interested in would be "Generalized Linear Models" which are not mentioned at all. After some search I might find "Logistic Regression" but then "Poisson Regression" is listed elsewhere.
* I would find it much more natural if broad inference frameworks and classes of statistical models were presented together. It might also make it less arbitrary which subsections are created and which not.
* I feel that simulation packages should be presented rather early on. However, this is also the group of packages where the inclusion and exclusion criteria are not sufficiently clear yet. Which packages are sufficiently geared towards power analysis to deserve to be mentioned here?
* Links would probably be an important addition, especially for worked examples/tutorials for simulation-based power analysis using certain frameworks.
* You only list one co-maintainer who I had troubles finding because he doesn't seem to be listed in your draft repository, yet. For such a broad topic such as power analysis it would be particularly important to include contributions from a set of co-maintainers with diverse backgrounds.

I hope to have some closer look at the draft and some of the packages included when I have some more time. But I thought that my first impressions above would already be a useful starting point for the discussion with the other CRAN Task View Editors.

Thanks again!

**Comment by tuxette** [comment] 2022-12-05 12:40
Hi @statisfactions : a short feedback on 2: in other task views (e.g., MissingData, part on Evaluation or Phylogenetics), packages oriented toward simulations for the related field are already included. So my personal point of view is that it would be better to continue in this direction than to have a broad TV on simulations that would address very different and unrelated simulation tasks.

**Comment by zeileis** [comment] 2023-10-04 06:40
Ethan @statisfactions, thanks again for your proposal and for your work on this topic in general. Given that the draft is now almost 2 years old and we haven't had any follow-up to our feedback from almost a year ago, I feel it's time to close this issue though. Thanks again & best wishes!

**Closed by zeileis** 2023-10-04 06:40 UTC
