### ISSUE TITLE
CRAN task view proposal: Pharmaverse

### ISSUE THREAD

**Issue by mstackhouse** [cran-task-views/ctv#60] opened 2024-01-19 19:12 UTC
# Scope

The packages included within the pharmaverse focus on a specific subset of clinical trial activities, specifically on the clinical reporting pipelines used within the pharmaceutical industry. These activities follow specific standards, such as [CDISC Data Standards](https://www.cdisc.org/) and [ICH E3](https://database.ich.org/sites/default/files/E3_Guideline.pdf). The scope of pharmaverse packages ranges from CRF (Case Report Forms - or data collection for a clinical trial) through clinical trial analysis reporting, including formatting of data to match SDTM (Study Data Tabulation Model) and ADaM (Analysis Data Model) standards, and production of TLGs (Tables, Listings, and Graphs). Furthermore, pharmaverse packages help supporting the orchestration activities of clinical trial data analysis through regulatory requirements.

The scope of the pharmaverse is only a small subset of the larger range of clinical trial activities for with R can be applied. For more information on R packages for clinical trials, see r view("ClinicalTrials"). Pharmaverse also has more resources outside of CRAN, which you can read about on [www.pharmaverse.org](http://www.pharmaverse.org/).

# Packages

## Study Data Tabulation Model (SDTM)

- datacutr

## Analysis Data Model (ADaM)

- admiralonco
- admiralophtha
- admiralvaccine

## Tables

- rtables
- Tplyr
- pharmaRTF
- tfrmt
- tidytlg

## Plots

- ggsurvfit

## Interactive

- tidyCDISC
- rhino

## Frameworks

- tern

## Electronic Submissions (eSUB)

- xportr
- datasetjson
- pkglite

## Metadata

- metacore
- metatools

## Utility

- logrx
- diffdf

## Package Validation

- valtools
- riskmetric

## Synthetic Data

- pharmaversesdtm
- pharmaverseadam

## Other Useful Packages

- flextable
- gt
- huxtable
- mmtable2
- ggplot2
- virdisLite
- tidyverse
- lintr
- styler
- renv

# Overlap

The most abundant potential overlap is with both [Clinical Trials](https://cran.r-project.org/web/views/ClinicalTrials.html) and [Survival](https://cran.r-project.org/web/views/Survival.html). The scope of pharmaverse itself is more narrow, focusing on activities and procedures around creating regulatory reports. 

# Maintainers

- Mike Stackhouse (@mstackhouse)
- Aaron Clark (@AARON-CLARK)
- Ross Farrugia (@rossfarrugia)

# Notes

A full draft of the task view is available here: https://github.com/pharmaverse/pharmaverse_task-view/blob/main/Pharmaverse.md

**Comment by zeileis** [comment] 2024-01-22 07:24
Thanks for the proposal! This is an interesting topic and the timing is also good, given that the "ClinicalTrials" task view is also going to be relaunched, see: https://github.com/cran-task-views/ctv/issues/59

For the current draft, I see the following main issues:

* Overlap with "ClinicalTrials": I think that the topic of clinical reporting could be a section within the ClinicalTrials task view, given that the list of dedicated packages is not excessively long. Separation into two task views is also feasible if the respective maintainers agree that this is a good idea and can come up with transparent criteria for placing packages into one or the other view. I'm tagging @ywang-gilead here: Ya, please also forward to your proposed co-maintainers for discussion.
* The "other useful packages" are probably not specific enough for this task view to be included. I would link to the "ReproducibleResearch" task view for this. If you see that some relevant packages are not covered there, yet, you can propose inclusion of them in an issue or pull request.
* The proposed title "Pharmaverse" does not work well in the context of CRAN Task Views. It will only be recognizable to those who know the project already. I guess "ClinicalReporting" would be more transparent to a wider audience.

**Comment by mstackhouse** [comment] 2024-02-12 20:09
@zeileis Both the ClinicalTrials and proposed Pharmaverse have met as a group. We mutually decided that right now it's better to keep our proposed task views separate and reassess in the future if it makes sense to combine them. We will continue to address feedback here. We will be updating with other proposed feedback you have suggested.

**Comment by zeileis** [comment] 2024-02-12 20:19
OK, thanks for the follow-up. Then we will assess the proposals separately. I have already raised my main concerns above. Maybe my fellow co-editors want to add to this list @rsbivand @eddelbuettel @tuxette

**Comment by tuxette** [comment] 2024-02-13 14:01
Thanks for the proposal. My impression is that your proposal would be a task view version of the website https://pharmaverse.org/ . Hence, at the moment, I don't clearly see its scope: As mentioned by @zeileis , it seems to be at the intersection of ClinicalTrial and ReproducibleResearch but I don't clearly see the focus specific to pharmaceutical studies or even clinical reporting. I you could elaborate a bit on that, it would help us better assessing your proposal. 
And, also for me, the name does not work well because "Pharmaverse" is not a field or a topic.

**Comment by mstackhouse** [comment] 2024-02-13 14:50
Hi @tuxette, 

The name change for the purpose of the task view makes sense. To additionally help clarify the scope, I'm thinking the title "RegulatoryClinicalReporting" might make sense, which is supported by the first paragraph of our the scope within the proposal. 

I think an additional clarification of scope is that that in addition to conforming to regulatory and industry standards, the packages in pharmaverse (or RegulatoryClinicalReporting) focus on _repeatability_ in addition to reproducibility. Given the standardization of regulatory reporting, these packages supporting making a pipeline that operates more like a factory than a bespoke analysis. So there's a heavy focus on efficiency.

**Comment by mstackhouse** [comment] 2024-02-13 14:56
# RegulatoryClinicalReporting

# Scope

The packages included within the RegulatoryClinicalReporting focus on a specific subset of clinical trial activities, specifically on the clinical reporting pipelines used within the pharmaceutical industry. These activities follow specific standards, such as [CDISC Data Standards](https://www.cdisc.org/) and [ICH E3](https://database.ich.org/sites/default/files/E3_Guideline.pdf). The scope of pharmaverse packages ranges from CRF (Case Report Forms - or data collection for a clinical trial) through clinical trial analysis reporting, including formatting of data to match SDTM (Study Data Tabulation Model) and ADaM (Analysis Data Model) standards, and production of TLGs (Tables, Listings, and Graphs). Furthermore, RegulatoryClinicalReporting packages help supporting the orchestration activities of clinical trial data analysis through regulatory requirements. **A specific distinction that sets these packages apart from those in task views such as r view("ClinicalTrials") is the focus on conformance to industry standards and efficiency. In addition to reproducibility, repeatability is a critical component of the clinical reporting pipeline given the volume of trials and analysis ongoing for pharmaceutical or medical organizations working with regulatory agencies,**

The scope of the RegulatoryClinicalReporting is only a small subset of the larger range of clinical trial activities for with R can be applied. For more information on R packages for clinical trials, see r view("ClinicalTrials"). Pharmaverse also has more resources outside of CRAN, which you can read about on [www.pharmaverse.org](http://www.pharmaverse.org/).

# Packages

## Study Data Tabulation Model (SDTM)

- datacutr

## Analysis Data Model (ADaM)

- admiralonco
- admiralophtha
- admiralvaccine

## Tables

- rtables
- Tplyr
- pharmaRTF
- tfrmt
- tidytlg

## Plots

- ggsurvfit

## Interactive

- tidyCDISC
- rhino

## Frameworks

- tern

## Electronic Submissions (eSUB)

- xportr
- datasetjson
- pkglite

## Metadata

- metacore
- metatools

## Utility

- logrx
- diffdf

## Package Validation

- valtools
- riskmetric

## Synthetic Data

- pharmaversesdtm
- pharmaverseadam

# Overlap

The most abundant potential overlap is with both [Clinical Trials](https://cran.r-project.org/web/views/ClinicalTrials.html) and [Survival](https://cran.r-project.org/web/views/Survival.html). Additionally, there is overlap with [ReproducibleResearch](https://cran.r-project.org/web/views/ReproducibleResearch.html). The scope of pharmaverse itself is more narrow, focusing on activities and procedures around creating regulatory reports. 

# Maintainers

- Mike Stackhouse (@mstackhouse)
- Aaron Clark (@AARON-CLARK)
- Ross Farrugia (@rossfarrugia)

# Notes

A full draft of the task view is available here: https://github.com/pharmaverse/pharmaverse_task-view/blob/main/Pharmaverse.md

**Comment by tuxette** [comment] 2024-02-20 09:53
Thanks @mstackhouse : it clarifies a bit the proposal for me. However, looking carefully at your new proposal, I have additional remarks:
- The topic organization is not clear for me at the moment: the headers are very specific and not organized in a way that makes sense for me (models before metadata for instance?);
- I see that quite a large proportion of cited packages are packages only deposited on github. While this is acceptable to have a few, this is a **CRAN** Task View so mainly focused on CRAN packages. Having a large proportion of github packages also jeopardize the ability to maintain the task view on the long term (since this packages tend to be a bit less maintained than packages published on CRAN).

**Comment by mstackhouse** [comment] 2024-02-20 15:12
Moving metadata up would be a fine adjustment for now. Otherwise, the flow of the packages is based on the clinical reporting lifecycle. In clinical reporting:

- SDTM Datasets are built on raw datasets
- ADaM datasets are built on SDTM datasets
- Tables, Listings, and Figures are built from ADaM datasets
- With a completed packages, eSubmission is completed. 

After that flow we have more of the utility packages placed. 

As for packages present on CRAN, the only one in the list that I've posted above that is _not_ present on CRAN is valtools, and that's my mistake. While the pharmaverse has more packages listed, I filtered out github packages and our view should only include packages present on CRAN. 

As you state that a large proportion are only on GitHub, please let me know if I'm mistaken in my list below.

All of these packages are included on CRAN currently: 
# Packages

## Study Data Tabulation Model (SDTM)

- datacutr https://cran.r-project.org/package=datacutr

## Analysis Data Model (ADaM)

- admiralonco https://cran.r-project.org/package=admiralonco
- admiralophtha https://cran.r-project.org/package=admiralophtha
- admiralvaccine https://cran.r-project.org/package=admiralvaccine

## Tables

- rtables https://cran.r-project.org/package=rtables
- Tplyr https://cran.r-project.org/package=Tplyr
- pharmaRTF https://cran.r-project.org/package=pharmaRTF
- tfrmt https://cran.r-project.org/package=tfrmt
- tidytlg https://cran.r-project.org/package=tidytlg

## Plots

- ggsurvfit https://cran.r-project.org/package=ggsurvfit

## Interactive

- tidyCDISC https://cran.r-project.org/package=tidyCDISC
- rhino https://cran.r-project.org/package=rhino

## Frameworks

- tern https://cran.r-project.org/package=tern

## Electronic Submissions (eSUB)

- xportr https://cran.r-project.org/package=xportr
- datasetjson https://cran.r-project.org/package=datasetjson
- pkglite  https://cran.r-project.org/package=pkglite

## Metadata

- metacore https://cran.r-project.org/package=metacore
- metatools  https://cran.r-project.org/package=metatools

## Utility

- logrx https://cran.r-project.org/package=logrx
- diffdf https://cran.r-project.org/package=diffdf

## Package Validation

- riskmetric https://cran.r-project.org/package=riskmetric

## Synthetic Data

- pharmaversesdtm https://cran.r-project.org/package=pharmaversesdtm
- pharmaverseadam https://cran.r-project.org/package=pharmaverseadam

**Comment by tuxette** [comment] 2024-02-21 18:12
Thanks @mstackhouse :
- About your remark on packages, I probably misunderstood your intent in the previous version: the current list of packages contains 23 packages and that is the entire list of packages that you intend to advertise in your task view? If so, @zeileis , can you comment on whereas this is a usual situation or not? (I sound low to me but I might be wrong). Also, what would be the "core" packages in this task view?
- Thank you for the clarification about the data flow. It is now clear for me for the first two sections but how some of the other sections fit into that 4-step workflow is still unclear. I don't know what to suggest to clarify but tentatively: can you group some of the very small sections that you have (like "Plots" and "Interactive" into larger sections "Data analysis" or whatever sounds fit to you with bullet points indicating the subtopics as it is standard in other task views). Also, trying to explain a bit the workflow (in the introduction and/or at beginning of sections) would help. See https://cran.r-project.org/web/views/Environmetrics.html for instance (I took one randomly).

**Comment by zeileis** [comment] 2024-02-21 23:00
Thanks for the useful discussions and updates, Mike @mstackhouse and Nathalie @tuxette. Some comments:

- 23 is indeed a rather low number of packages. The smallest task views so far have 30-35 packages. That's why I suggested to merge the proposal with the ClinicalTrials task view. However, given that the two teams agreed that keeping the two views separate, I think it's ok. The sharp focus will clearly facilitate maintenance - and also the task view is likely to grow in the future.
- Having said that, I think that there is no need to impose a strict CRAN-only policy. If there are some sufficiently interesting/promising packages on GitHub, it's certainly ok to link these as well.
- The new scope description still mentions "pharmaverse" without much explanation/introduction. I think it would be good to clarify that the task view is not simply a listing of pharmaverse packages. It's fine to explain that this is an important initiative but there can be packages in the task view that are not part of the pharmaverse (and vice versa).
- Better explaining the workflow as suggested by @tuxette will be helpful.

**Comment by tuxette** [comment] 2024-08-16 09:59
@mstackhouse : I do not see activity for this proposal since February. However, to me, we were heading to something interesting with the few minor adjustments that have been suggested. Do you still plan to submit this task view?

**Comment by zeileis** [comment] 2024-09-22 21:12
Unfortunately, we did not have any follow-up in more than half a year. Hence I'm closing this issue/proposal now. However, I agree with Nathalie @tuxette that we had been quite close to an interesting submission. Michael @mstackhouse, if you do feel that you want to move this forward, please post a new issue incorporating the feedback we provided.

**Closed by zeileis** 2024-09-22 21:12 UTC
