### ISSUE TITLE
CRAN task view proposal: CausalInference

### ISSUE THREAD

**Issue by imkemayer** [cran-task-views/ctv#15] opened 2022-01-03 15:51 UTC
### Scope
This CRAN Task View proposal contains a list of packages useful for causality related analyses, including causal discovery and mainly causal inference. On top of the list of reviewed packages, we plan to include a list of selected books and articles that make use of some of these packages and that are helpful to get a better understanding of the topic of causality on concrete examples implemented in R code. Causal analyses can be performed in many different ways, depending on the context, the data and the assumptions made by the analyst. With this task view we aim at assisting the user in the choice of adequate implemented methods for his/her problem and data to analyze.

Since some of this proposed CTV maintainers are also maintainers of the already existing MissingData CTV, we followed a similar approach to select packages into the task view. To be considered for inclusion, the package must be useful for running causal analyses, be it causal discovery, causal inference or causal prediction, either by providing analysis tools or relevant datasets. Furthermore the package should satisfy the following technical criteria: the date of first release of the package should be more than one year old and the date of last update or the frequency of updates should reflect a regular maintenance of the package.

### Packages
Please see https://www.imkemayer.com/files/causalinference for a comprehensive list and preview of the Task View. It currently consists of 150 packages (including 9 core packages).

### Overlap
There might be some overlap between packages in the ClinicalTrials and ExperimentalDesign CTVs, but to minimize this overlap, our CTV proposal focuses on issues that arise mainly in observational (or quasi-experimental) data analysis and less on experimental design.
Since causal inference is an important topic in econometrics, there is also some overlap with the Econometrics CTV but we aim at targeting an audience from a wider range of domains, for example with problems from social and health care applications.
Missing data handling and causal inference share some similar methods and certain packages can be used in the two contexts but with different goals. Therefore overlap between this present proposal and the MissingData CTV is possible but does not imply redundancy. 

### Maintainers
The primary maintainer is Imke Mayer (@imkemayer). Current co-maintainers are Pan Zhao (@panzhaooo), Nick Huntington-Klein (@NickCH-K) and Julie Josse (@julierennes). 

Collaborators of these maintainers have already agreed to assist in the maintenance of the task view to ensure constant updates and corrections where necessary.

**Comment by NickCH-K** [comment] 2022-01-08 01:09
Hi! Thanks for inviting me to this. I hope commenting here is the right way to interact.

Many of the bullet points refer to areas I don't know much about, but some are for ones I do! Some notes:

- I disagree with this in the opener: "There do not exist basic R functions to do causal analyses straight away" - not true! You can (and people do) do good causal analysis with `lm()`, or heck even `mean()` or `aggregate()` or a million other functions. If you mean that there aren't basic R functions that directly implement standard CI designs with all the bells and whistles, that's more accurate.
- The package **fixest** should probably be included under "Regression models where the causal estimand is a regression parameter". This package is in most ways an improvement over **estimatr** for that task and also for instrumental variables. **fixest** also includes a number of tools for working with difference-in-difference designs, including the Sun & Abraham estimator, and should be included in the DID section. Keeping track, **fixest** should probably take **estimatr**'s place in "Regression models" and "instrumental variables", and should be added to DID.
- How does **estimatr** do IPW designs? Is it just that it accepts weights? Most regression models do, including `lm()`, so I'm not sure this is a useful entry there. Unless I'm missing a specific application they have.
- There should probably be an entry for fixed effects designs. **fixest** pops up there again, for both linear and GLM fixed effects models, and fixed effects combined with instrumental variables, for which **plm** and **lfe** are also options. There is also **alpaca** for GLM fixed effects.
- In the RDD section I'd probably mention **rdrobust** first, and then afterwards go into the rest of the package family, since `rdrobust` is the main one you'd use. Also suggest the addition of **RDHonest** for inference under poorly-behaving running variables
- Minor typo: extra space in the DAGitty link.
- Additional matching packages: **cem** for coarsened exact matching, and **ebal** for entropy balancing
- Also in Matching: the **Matching** package, already listed, also does k-nearest-neighbor matching.
- Recommend an addition of **tidysynth** to synthetic control for its ease of syntax.
- Might be worth the addition of **estudy2** for event study estimation, although perhaps this is too niche

**Comment by zeileis** [comment] 2022-01-09 10:12
Hi everyone, especially thanks to @imkemayer for starting the discussion here and @NickCH-K for providing detailed feedback!

My first impression is that this looks very promising. The number of packages is ok but if there were something to sharpen the focus, it might help and facilitate maintenance in the future.

Nathalie @tuxette said that she will try to have a closer look soon and provide some more feedback. But the discussion and decision may take some more weeks as we are currently still very busy with the transition of the old task views to the new infrastructure (as mentioned in the [README](../../ctv/blob/main/README.md)).

**Comment by tuxette** [comment] 2022-01-11 18:07
My feedback:

- Overall, I find the task view clear and well documented.
- I have converted it, by pull request, to the new md format and fixed a few typos that I saw. I also have to mention that: some of the task views mentioned in the links at the end of your task view were not cited in the text: they have disappeared with the new format (these are: Econometrics, MetaAnalysis, Survival). @zeileis : am I wrong saying that you expect them to be cited in the text of the task view?
- One of the (maybe naive) questions that I had reviewing you task view is why didn't you include any reference to SEM packages (**sem**, **lavaan** or **SEMgraph**, the last one being a bit too recent probably)? Isn't it because your TV is a bit too focused on methods for clinical trials (as suggested by the organization of the first sections) and lacks a bit of references from the social analysis side? (I might be wrong.)
- Another naive suggestion: I would have expected the package **bnlearn** to be cited as well (maybe as a core package). Again, I might be missing something here.

**Comment by tuxette** [comment] 2022-01-11 18:09
Ref to pull request: https://github.com/imkemayer/causal-inference-taskview/pull/1

**Comment by zeileis** [comment] 2022-01-11 23:28
Thanks for the productive discussion so far and especially to Nathalie @tuxette for having a closer look and writing up her feedback. Some additions:

* I agree that this is nicely done and already quite mature.
* I also think that the focus on observational data is the right approach. I would even push this further to sharpen the focus of the task view. In the intro text of the task view this should also be explained explicitly so that it is clear to all readers what is in the task view and what is not.
* In the sections on _instrumental variables_ (IV) and _regression discontinuity design_ (RDD) I think that it would make sense to link explicitly to the Econometrics task view where we already have paragraphs on these topics. And then I would only list the packages where it is really important to have them in the CausalInference task view as well.
* Side remark 1: My feeling is that the Econometrics task view is the more natural home for these sections as most of the literature originates there, to the best of my knowledge. But I might be wrong. In any case, if you think that the IV and RDD discussions in the Econometrics task view should be improved, it would be great if you (especially @imkemayer and/or @NickCH-K) open an issue and/or make a PR in the corresponding repository: <https://github.com/cran-task-view/Econometrics/>.
* Side remark 2: Nathalie is correct that task view should be cited explicitly in the text of the task view and not just added in the links at the end. The citations in concrete sections will make it a lot easier for the readers to know where they have to search further. The links at the end are then added automatically in the HTML version (similar to references at the end of a paper).
* Regarding _structural equation modeling_ (SEM) I would recommend a similar strategy as for IV and RDD. Only list those package that are really important/specific for causal inference and then link to the Psychometrics task view that already has a dedicated section on SEMs.

**Comment by zeileis** [comment] 2022-04-12 22:53
Imke @imkemayer, now that we have officially relaunched the task views workflow on CRAN, we can make progress on new task view proposals as well. Hence I wondered what the status of this proposal is.

**Comment by julierennes** [comment] 2022-04-13 12:04
@zeileis  We have a meeting planned in two weeks to improve it again and I think we will have another contributor/maintainer as well. Keep you inform asap.

**Comment by zeileis** [comment] 2022-04-14 00:31
OK, thanks!

**Comment by davidjohannesmeyer** [comment] 2022-05-18 16:54
I am a bit late to the party, but just a small comment:
The current state already looks very comprehensive and well-structured to me. Shouldn't there be a reference to the graphical models task view?  (pcalg package and graphical models are briefly mentioned).

**Comment by imkemayer** [comment] 2022-05-18 17:02
Thanks @davidjohannesmeyer for this comment, indeed that reference to the graphical models ctv should be added to complete the part on the causal structure learning.

**Comment by tuxette** [comment] 2022-06-03 10:59
Hi @imkemayer ! Do you consider the last update of the TV as a new proposal? There has not been much activity in the current issue during last month but I don't think that all remarks from @zeileis and myself have been addressed. It does not mean that they all need to be taken into account but a point-by-point answer here would be useful to understand your point and make this TV move forward. Thanks for your work!

**Comment by imkemayer** [comment] 2022-06-07 06:54
Hi @tuxette, thank you for the reminder. Indeed we haven't addressed all comments and suggestions yet but we will do it this week together with @julierennes and come back to you with a point-by-point answer.

**Comment by imkemayer** [comment] 2022-06-07 16:08
Thank you all for your suggestions and remarks. As suggested by @tuxette, we provide a point-by-point reply to your remarks:

@NickCH-K (adressed by commit [#a48e507](https://github.com/imkemayer/causal-inference-taskview/commit/a48e507494d5f2ac3a3a064aea8e6a6344f6cb44))
- _First sentence:_ Thanks for this suggestion, your formulation is indeed more accurate, so we replaced the previous phrase with it.
- _fixest package:_ We weren't aware of this package but it is indeed very complete and well documented and we have added it as a core package to the sections you suggested.
- _estimatr and IPW:_ estimatr computes by default robust standard errors and confidence intervals, which is why we have added it to this IPW section
- _Fixed effects designs:_ We have included these packages now for fixed effects designs, except the lfe package which is no longer maintained and will probably be archived in the near future.
- _RDD section:_ We followed your suggestion and put rdrobust first. However we didn't add RDHonest because it is not yet on CRAN. But we have added it to our waiting list (packages to check again later because they are not yet on CRAN)
- _Matching section:_ We only added the cem package because the ebal package has not been updated since 2014 and there are notes in the CRAN checks of this package. Thank you for the additional info on the Matching package
- _tidysynth_: Thanks for this pointer, it is now in the synthetic control section
- _estudy2_: It is also listed in the Finance CTV but we have also added it in the "Specific application fields" section

@tuxette and @zeileis (addressed by commits [#9231acf](https://github.com/imkemayer/causal-inference-taskview/commit/9231acf9c621895086c483a28a077cda6736db8c) and [#9231acf](https://github.com/imkemayer/causal-inference-taskview/commit/f1e6a4ce40e5c3a42b8e0003a43e500172111aed))
- _Sharpen the focus of the task view:_ In the intro text of the task view this should also be explained explicitly so that it is clear to all readers what is in the task view and what is not.
- _RDD and IV:_ I just posted a [comment](https://github.com/cran-task-views/Econometrics/issues/10#issuecomment-1148838389) in the open issue in the Econometrics task view repo for additional packages (sorry again for the delayed response to your suggestions!). For the RDD I agree that the Econometrics task view is a more natural choice, for the IV section I would still keep most of the packages in the CI task view as well because it's part of the standard methods in CI (even if they are mostly applied by economists).
- _Citing other task views:_ Thanks for clarifying this. We have now added the references to the other task views in the text.
- _Structural equation modeling:_ We have added references to the GraphicalModels and Psychometrics task views and only keep the packages specific for causal discovery and causal inference.

**Comment by tuxette** [comment] 2022-06-07 18:57
Thanks for the corrections and the point-by-point answer. This clarifies things for me. As a minor remark, I might have missed something but wouldn't it be best to directly include @NickCH-K as one of the co-maintainers?

**Comment by imkemayer** [comment] 2022-06-08 16:46
Indeed @tuxette, we have not included him yet but finally did it in the most recent commit #8bec5d6
Thanks for pointing this out to us!

**Comment by tuxette** [comment] 2022-06-08 19:41
I am under the impression that we could move forward to the publication of the TV: what do you think, @zeileis ?

**Comment by zeileis** [comment] 2022-06-09 19:01
Given they have reached out from someone in political science, I think it would be nice to wait for their feedback.

But after that we can quickly move forward. Formally, we need a third endorsement from one of the CRAN Task View Editors. A thumbs up reaction would be enough, @rsbivand @eddelbuettel @rociojoo @davidjohannesmeyer

**Comment by eddelbuettel** [comment] 2022-06-09 19:05
What is the current URL?  For https://github.com/imkemayer/causal-inference-taskview/ I get a 404.

**Comment by zeileis** [comment] 2022-06-09 19:21
Does this work for you: https://www.imkemayer.com/files/causalinference ? Sorry for not checking that before...

**Comment by zeileis** [comment] 2022-06-09 19:24
One small comment and question about the instrumental variables section in the task view:

* Why are `ivmodel` and `ivpack` listed explicitly rather than `ivreg`? I'm biased here obviously...possibly I'm overlooking important advantages of these packages.
* For referring to specific sections from the Econometrics task view you can use `view("Econometrics", "Instrumental variables")` now. This requires the very latest development version of `ctv` from R-Forge, though (committed a couple of minutes ago).

**Comment by imkemayer** [comment] 2022-06-10 07:59
Thank you @zeileis for pointing out this missing package. Sorry for the oversight, we missed it when searching by key words for potential packages to review. I fixed the search script and now it finds your package.

And thanks for offering the new option to directly refer to a specific section of another task view. We now use it for IV and RDD.

**Comment by zeileis** [comment] 2022-06-24 01:29
Thanks for all your work Imke @imkemayer & Co! I've now completed the transfer of the repository to the cran-task-views org and did some touch-ups, see: <https://github.com/cran-task-views/CausalInference>
In particular:
- Invited Julie @julierennes and Nick @NickCH-K to be co-maintainers on GitHub as well (in addition to Pan @panzhaooo and Noah @ngreifer who had already been added on GitHub).
- Dropped Nathalie @tuxette and myself as we have access through the org anyway.
- Use the standardized "README" and "About" from cran-task-views.
- Move the .md source file top-level and drop the rendered .html (which will be on CRAN).
- A few style touch-ups in the .md.
- I also updated some of the code in the "R" directory which was partially outdated. It's not urgent but maybe you could have a look at the code in that directory whether everything is still up to date. Also the data directory can maybe merged into the R directory as well.

So I think we are good to go for a CRAN release. Imke, maybe you can have a quick last look whether everything is in order? Then I'll release on CRAN.

**Comment by imkemayer** [comment] 2022-06-24 12:05
Thank you Achim @zeileis for this quick and complete touch-up of the transferred repository! I've had a look at the changes and they're all fine for me. Also I merged the data and R directories as you suggested.

**Comment by zeileis** [comment] 2022-06-24 13:51
Fantastic, we're live: 🎉

https://CRAN.R-project.org/view=CausalInference

And advertised on Twitter: https://twitter.com/AchimZeileis/status/1540329721623347200

Thanks everyone for your efforts!

**Closed** 2022-06-24 13:51 UTC
